name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    ############################################
    # 1. CodeQL SAST
    ############################################
    - name: Init CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Analyze CodeQL
      uses: github/codeql-action/analyze@v3

    ############################################
    # 2. Bandit
    ############################################
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r api --severity-level high

    ############################################
    # 3. Scan d√©pendances
    ############################################
    - name: Install Safety
      run: pip install safety

    - name: Dependency Scan
      run: safety check -r requirements.txt

    ############################################
    # 4. Build Docker
    ############################################
    - name: Build Docker Image
      run: docker build -t devsecops-api .

    ############################################
    # 5. Trivy
    ############################################
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-api
        severity: CRITICAL,HIGH
        exit-code: 1
